name: Leaderboard Creation 

on: push

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: create_output
        id: output
        run: |
          sudo apt-get install -y pandoc 
          mkdir output # create output dir
          cp -R static output/static # copy static dir 
          ./convert.sh # convert files with pandoc
      
      - uses: actions/upload-artifact@v4
        with:
          name: page
          path: output

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
      
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: page
        path: .
    - uses: actions/configure-pages@v4
    - uses: actions/upload-pages-artifact@v3
      with:
        path: .
    - id: deployment
      uses: actions/deploy-pages@v4
 
